input LoginInput {
  email: String!
  password: String!
}

type Mutation {
  login(input: LoginInput!): User!
  signUp(input: SignUpInput!): User!
}

type Query {
  me: User
}

input SignUpInput {
  email: String!
  name: String!
  password: String!
}

type User {
  email: String!
  id: ID!
  name: String!
}
